Repository kookmin-sw/capstone-2024-14, pull requests merged in 2024-03, with the labels that each got.

#14 Side bar(Nav) 기본 UI 구현
  frontend/package.json
  frontend/src/components/common/.keep
  frontend/src/components/common/Nav.js
  frontend/src/core/router.js
  frontend/src/pages/test.js
  frontend/yarn.lock
Labels: frontend, 💄 design

#17 Init: 폴더 구조 및 환경 세팅 #16
  server/src/main/java/com/capstone/server/code/UserErrorCode.java
  server/src/main/java/com/capstone/server/dto/UserCreateRequestDto.java
  server/src/main/java/com/capstone/server/dto/UserUpdateRequestDto.java
  server/src/main/java/com/capstone/server/exception/GlobalExceptionHandler.java
  server/src/main/java/com/capstone/server/exception/UserException.java
  server/src/main/java/com/capstone/server/model/UserEntity.java
  server/src/main/java/com/capstone/server/repository/UserRepository.java
  server/src/main/java/com/capstone/server/response/ErrorResponse.java
  server/src/main/java/com/capstone/server/response/SuccessResponse.java
Labels: backend, ✨feat

#23 Feature/21
  .github/workflows/feature.yml
  .github/workflows/main.yml
  server/.gitignore
  server/Dockerfile
  server/src/main/resources/application-local.properties
Labels: backend

#28 github branch protection test
  server/src/main/java/com/capstone/server/ServerApplication.java
Labels: 🧹 chore

#34 Docs : 중간발표 대비 readme.md 내용 추가
  README.md
Labels: 📃 doc

#35 Docs : 중간평가 대비 github Page 추가
  index.md
Labels: 📃 doc

#36 update: Modify Yolov5 Detection Image Saving Name
  ai/yolov5-crowdhuman/.cph/.detect.py_72c1b858a876b19a9677f89677b195d5.prob
  ai/yolov5-crowdhuman/detect.py
  ai/yolov5-crowdhuman/remove.txt
  ai/yolov5-crowdhuman/utils/datasets.py
Labels: ai

#38 update: create a JSON file for 2-stage model
  ai/yolov5-crowdhuman/detect.py
Labels: ai

#42 Update: aspect ratio adjustment
  ai/yolov5-crowdhuman/detect.py
Labels: ai
