Repository kookmin-sw/capstone-2024-14, pull requests merged in 2024-04, with the labels that each got.

#52 Update and Refactor: text encoding and custom dataset path changed
  ai/TextReID/lib/config/paths_catalog.py
  ai/TextReID/lib/data/encode/encoding.py
  ai/TextReID/lib/data/encode/word_dict/test.json
  ai/TextReID/lib/data/metrics/evaluation.py
  ai/TextReID/lib/engine/inference.py
  ai/TextReID/test_net.py
Labels: ai, 🔨 refactor

#56 Docs : readme.md 수정, 중간보고서, 발표자료 업로드
  README.md
  docs/중간 발표자료 -Pro_bee.pdf
  docs/중간보고서-Pro_bee.pdf
Labels: 📃 doc

#61 Feat : 실종 정보 등록 화면 기본 UI 구현
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/components/addMisingPerson/GuardianInfo.js
  frontend/src/components/addMisingPerson/IntelligentSearchInfo.js
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/src/components/addMisingPerson/WearingInfo.js
  frontend/src/components/common/SearchBox.js
  frontend/src/core/router.js
  frontend/src/data/WearingItemMenu.js
  frontend/src/pages/AddMissingPersonPage.js
Labels: frontend, 💄 design

#63 Feat : 도로명 주소 검색 기능 구현
  frontend/package.json
  frontend/src/components/addMisingPerson/IntelligentSearchInfo.js
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/src/components/common/SearchBox.js
  frontend/yarn.lock
Labels: frontend, ✨feat

#72 Feat: actuator for health check
  .vscode/launch.json
  server/build.gradle
Labels: backend, 📬 API

#74 Fix: dataset initialization upload
  ai/TextReID/lib/data/datasets/__init__.py
  ai/TextReID/lib/data/datasets/concat_dataset.py
  ai/TextReID/lib/data/datasets/cuhkpedes.py
Labels: ai

#78 CHORE : ai 모델 파이썬 버전 동기화, requirement통일 및 운영체제, 실행환경 세팅
  .gitignore
  ai/README.MD
  ai/TextReID/README.md
  ai/TextReID/requirements.txt
  ai/TextReID/runs/Apr11_03-30-47_jongbin-System-Product-Name/events.out.tfevents.1712773847.jongbin-System-Product-Name.44635.0
  ai/requirements.txt
  ai/yolov5-crowdhuman/.gitignore
  ai/yolov5-crowdhuman/Dockerfile
  ai/yolov5-crowdhuman/README.md
  ai/yolov5-crowdhuman/app-image-config-input.json
  ai/yolov5-crowdhuman/default-user.settings.json
  ai/yolov5-crowdhuman/detect.py
  ai/yolov5-crowdhuman/requirements.txt
Labels: ai, backend

#81 Feat: Missing-People GET, POST API
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/UserApiController.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateResponseDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleResponseDto.java
  server/src/main/java/com/capstone/server/dto/UserCreateRequestDto.java
  server/src/main/java/com/capstone/server/exception/CustomException.java
  server/src/main/java/com/capstone/server/exception/GlobalExceptionHandler.java
  server/src/main/java/com/capstone/server/exception/UserException.java
  server/src/main/java/com/capstone/server/model/CCTVEntity.java
  server/src/main/java/com/capstone/server/model/GuardianEntity.java
  server/src/main/java/com/capstone/server/model/MissingPeopleDetailEntity.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java
  server/src/main/java/com/capstone/server/model/SearchResultEntity.java
  server/src/main/java/com/capstone/server/model/UserEntity.java
  server/src/main/java/com/capstone/server/model/enums/BagType.java
  server/src/main/java/com/capstone/server/model/enums/BodyType.java
  server/src/main/java/com/capstone/server/model/enums/BottomType.java
  server/src/main/java/com/capstone/server/model/enums/Color.java
  server/src/main/java/com/capstone/server/model/enums/Gender.java
  server/src/main/java/com/capstone/server/model/enums/HairStyle.java
  server/src/main/java/com/capstone/server/model/enums/TopType.java
  server/src/main/java/com/capstone/server/model/enums/userEnum.java
  server/src/main/java/com/capstone/server/repository/GuardianRepository.java
  server/src/main/java/com/capstone/server/repository/MissingPeopleDetailRepository.java
  server/src/main/java/com/capstone/server/repository/MissingPeopleRepository.java
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/response/ErrorResponse.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/UserService.java
Labels: backend, 📬 API

#83 실종자 리포트 화면(메인) 기본 UI 구현
  frontend/src/components/common/InputForm.js
  frontend/src/components/common/ResultView.js
  frontend/src/components/missingPersonReport/BasicInfo.js
  frontend/src/components/missingPersonReport/ReportList.js
  frontend/src/components/missingPersonReport/ReportMap.js
  frontend/src/components/missingPersonReport/ReportTabs.js
  frontend/src/components/missingPersonReport/StepProgress.js
  frontend/src/core/router.js
  frontend/src/pages/MissingPersonReportPage.js
  frontend/src/styles/global.js
Labels: frontend, 💄 design

#86 Side nav bar 수정 및 페이지 연결
  frontend/src/components/common/Nav.js
  frontend/src/core/router.js
Labels: frontend

#87 Feat : missing-people by id GET API 개발
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: backend, 📬 API

#88 Chore: run time modify
  ai/yolov5-crowdhuman/detect.py
  ai/yolov5-crowdhuman/detection.json
Labels: ai

#92 Update: code for making query
  ai/make-query/_togle2sentence.ipynb
  ai/make-query/_togle2sentence.py
Labels: ai

#94 Feat : ai서버와 연결
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/UserApiController.java
  server/src/main/java/com/capstone/server/dto/DetectionRequestDto.java
  server/src/main/java/com/capstone/server/dto/DetectionResponseDto.java
  server/src/main/java/com/capstone/server/service/DetectService.java
Labels: backend

#97 Feat: S3 관련 API 개발
  server/build.gradle
  server/src/main/java/com/capstone/server/config/S3Config.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/S3Controller.java
  server/src/main/java/com/capstone/server/dto/S3DownloadResponseDto.java
  server/src/main/java/com/capstone/server/dto/S3UploadResponseDto.java
  server/src/main/java/com/capstone/server/dto/SearchHistoryDto.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/enums/BagType.java
  server/src/main/java/com/capstone/server/model/enums/Step.java
  server/src/main/java/com/capstone/server/response/SuccessResponse.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/S3Service.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
  server/src/main/java/com/capstone/server/service/UserService.java
Labels: backend, 📬 API

#100 Chore : 실종정보등록 화면 반응형 적용
  frontend/src/components/addMisingPerson/GuardianInfo.js
  frontend/src/components/addMisingPerson/IntelligentSearchInfo.js
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/src/components/addMisingPerson/WearingInfo.js
  frontend/src/components/common/SearchBox.js
  frontend/src/data/WearingItemMenu.js
  frontend/src/pages/AddMissingPersonPage.js
Labels: frontend, 💄 design

#99 Chore: get image path by user input
  ai/TextReID/lib/config/paths_catalog.py
  ai/TextReID/lib/data/datasets/cuhkpedes.py
Labels: ai, 🧹 chore

#105 Feat : 실종자 리포트 화면(지능형탐색) 기본 UI 구현
  frontend/src/components/common/ResultView.js
  frontend/src/components/missingPersonReport/ReportTabs.js
  frontend/src/components/reportIntelligent/IntelligentBasicInfo.js
  frontend/src/components/reportIntelligent/IntelligentMap.js
  frontend/src/components/reportIntelligent/IntelligentSearchOption.js
  frontend/src/components/reportIntelligent/IntelligentSearchResult.js
  frontend/src/pages/MissingPersonReportPage.js
  frontend/src/styles/global.js
Labels: frontend, 💄 design

#108 Feat : 실종자 리포트 스크롤 기능 구현
  frontend/src/pages/MissingPersonReportPage.js
Labels: frontend, ✨feat

#102 Fix: image name from add twice extension to add once extension
  server/src/main/java/com/capstone/server/dto/S3DownloadResponseDto.java
  server/src/main/java/com/capstone/server/dto/S3UploadResponseDto.java
  server/src/main/java/com/capstone/server/service/S3Service.java
Labels: 🐞 bug, backend

#113 이미지 디렉토리 argument로 받아오기
  ai/TextReID/lib/config/defaults.py
  ai/TextReID/lib/config/paths_catalog.py
  ai/TextReID/lib/data/build.py
  ai/TextReID/lib/data/datasets/cuhkpedes.py
  ai/TextReID/lib/engine/inference.py
  ai/TextReID/test_net.py
Labels: ai, 🔨 refactor, 🧹 chore

#118 Feat : ai서버에 쿼리 생성 기능 추가
  .gitignore
  ai/README.MD
  ai/TextReID/lib/utils/logger.py
  ai/TextReID/test_net.py
  ai/app.py
  ai/make_query/__init__.py
  ai/make_query/_togle2sentence.ipynb
  ai/make_query/_togle2sentence.py
  ai/make_query/make_query.py
Labels: ai, backend

#122 Feat : AIServer 이미지 s3업로드 기능 추가
  ai/README.MD
  ai/app.py
  ai/yolov5_crowdhuman/detect.py
Labels: ai, backend, 📬 API

#123 Feat : create MissingPeople기능에 ai서버 연동
  ai/README.MD
  ai/app.py
  ai/make_query/make_query.py
  ai/requirements.txt
  ai/yolov5_crowdhuman/detect.py
  server/src/main/java/com/capstone/server/config/AppConfig.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/DetectionRequestDto.java
  server/src/main/java/com/capstone/server/dto/DetectionResponseDto.java
  server/src/main/java/com/capstone/server/dto/DetectionResultDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateResponseDto.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java
  server/src/main/java/com/capstone/server/repository/CCTVRepository.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
Labels: backend, 📬 API

#130 Feat : sms발송기능 추가
  .gitignore
  server/build.gradle
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/SmsRequestDto.java
  server/src/main/java/com/capstone/server/dto/SmsResponseDto.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: backend

#132 Feat : 의뢰인용 메인 화면 기본 UI 구현
  frontend/src/components/common/InputForm.js
  frontend/src/components/guardianMain/CustomSteps.js
  frontend/src/components/guardianMain/ProfileCard.js
  frontend/src/components/guardianMain/StepContents.js
  frontend/src/components/guardianMain/UploadImage.js
  frontend/src/core/router.js
  frontend/src/pages/GuardianMainPage.js
Labels: frontend, 💄 design
