Repository kookmin-sw/capstone-2024-14, pull requests merged in 2024-05, with the labels that each got.

#135 Feat: Kafka 도입
  .github/workflows/main.yml
  server/.gitignore
  server/build.gradle
  server/docker-compose.yml
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/config/KafkaConsumerConfig.java
  server/src/main/java/com/capstone/server/config/KafkaProducerConfig.java
  server/src/main/java/com/capstone/server/controller/CCTVController.java
  server/src/main/java/com/capstone/server/controller/KafkaProducerController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/CCTVDto.java
  server/src/main/java/com/capstone/server/dto/DetectionRequestDto.java
  server/src/main/java/com/capstone/server/dto/KafkaDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleResponseDto.java
  server/src/main/java/com/capstone/server/dto/SearchHistoryDto.java
  server/src/main/java/com/capstone/server/model/CCTVEntity.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java
  server/src/main/java/com/capstone/server/model/enums/BagType.java
  server/src/main/java/com/capstone/server/model/enums/BodyType.java
  server/src/main/java/com/capstone/server/model/enums/BottomType.java
  server/src/main/java/com/capstone/server/model/enums/Color.java
  server/src/main/java/com/capstone/server/model/enums/Gender.java
  server/src/main/java/com/capstone/server/model/enums/HairStyle.java
  server/src/main/java/com/capstone/server/model/enums/MissingPeopleSortBy.java
  server/src/main/java/com/capstone/server/model/enums/PoliceStation.java
  server/src/main/java/com/capstone/server/model/enums/Status.java
  server/src/main/java/com/capstone/server/model/enums/Step.java
  server/src/main/java/com/capstone/server/model/enums/TopType.java
  server/src/main/java/com/capstone/server/repository/CCTVRepository.java
  server/src/main/java/com/capstone/server/repository/GuardianRepository.java
  server/src/main/java/com/capstone/server/repository/MissingPeopleDetailRepository.java
  server/src/main/java/com/capstone/server/repository/MissingPeopleRepository.java
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/service/CCTVService.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
  server/src/main/java/com/capstone/server/service/KafkaProducerService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
Labels: backend, ✨feat, 📬 API

#136 Feat : 의뢰인용 이미지 선별 화면 기본 UI 구현
  frontend/src/components/guardianMain/StepContents.js
  frontend/src/components/guardianSelect/AllResultList.js
  frontend/src/components/guardianSelect/SelectImgList.js
  frontend/src/core/router.js
  frontend/src/pages/GuardianMainPage.js
  frontend/src/pages/GuardianSelectImgPage.js
Labels: frontend, 💄 design

#138 Fix : API버그수정
  ai/README.MD
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateResponseDto.java
  server/src/main/java/com/capstone/server/dto/StepDto.java
  server/src/main/java/com/capstone/server/exception/CustomException.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java
  server/src/main/java/com/capstone/server/model/enums/SearchStatus.java
  server/src/main/java/com/capstone/server/model/enums/Status.java
  server/src/main/java/com/capstone/server/model/enums/Step.java
  server/src/main/java/com/capstone/server/model/enums/StepDetail.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: 🐞 bug, backend

#141 Feat : 실종자 리스트 기본 UI 구현
  frontend/src/assets/images/emptyProfile.svg
  frontend/src/components/common/Nav.js
  frontend/src/components/missingPersonList/CardView.js
  frontend/src/core/router.js
  frontend/src/data/DummyData.js
  frontend/src/pages/MissingPersonListPage.js
Labels: frontend, 💄 design

#133 Fix and Update: 인코더 및 학습 코드 수정
  ai/TextReID/README.md
  ai/TextReID/lib/data/encode/encoding.py
  ai/TextReID/lib/engine/inference.py
  ai/TextReID/lib/models/backbones/gru.py
  ai/TextReID/train_net.py
Labels: 🐞 bug, 📃 doc, ai

#145 Chore : FrontEnd와 연결하기위한 파라미터 수정
  ai/README.MD
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleResponseDto.java
  server/src/main/java/com/capstone/server/exception/CustomException.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/enums/Color.java
  server/src/main/java/com/capstone/server/model/enums/Gender.java
  server/src/main/java/com/capstone/server/model/enums/MissingPeopleType.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: 🐞 bug, backend

#150 Feat : 실종정보 등록 api 연결
  .gitignore
  frontend/.env
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/components/addMisingPerson/IntelligentSearchInfo.js
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/src/components/addMisingPerson/WearingInfo.js
  frontend/src/components/common/SearchBox.js
  frontend/src/core/api/index.js
  frontend/src/data/WearingItemMenu.js
  frontend/src/pages/AddMissingPersonPage.js
  frontend/yarn.lock
Labels: frontend, 📬 API

#149 Fix: main.yml 을 capstone aws 계정 ec2 t2.medium 으로 변경
  .github/workflows/main.yml
  server/src/main/java/com/capstone/server/model/enums/Color.java
Labels: backend, Infra

#151 [AI] last layer fine-tuning 및 train 전용 inference code 추가
  ai/TextReID/lib/data/metrics/train_evaluation.py
  ai/TextReID/lib/engine/train_inference.py
  ai/TextReID/lib/engine/trainer.py
  ai/TextReID/lib/solver/build.py
  ai/TextReID/train_net.py
Labels: ai, 🧹 chore

#152 Feat : 실종자 리스트(현황) 일부 api 연결
  frontend/package.json
  frontend/src/components/missingPersonList/CardView.js
  frontend/src/core/api/index.js
  frontend/src/pages/MissingPersonListPage.js
  frontend/yarn.lock
Labels: frontend, 📬 API

#154 Fix: set Ubuntu local time in github actions
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: 🐞 bug, backend, 📬 API

#159 Feat : 실종정보등록 유효성 검사 기능 추가
  frontend/package.json
  frontend/src/components/addMisingPerson/GuardianInfo.js
  frontend/src/components/addMisingPerson/IntelligentSearchInfo.js
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/yarn.lock
Labels: frontend, ✨feat

#160 Feat : 실종자 상세정보 및 검색기록 리스트 가져오기 api 추가
  server/docker-compose.yml
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleDetailResponseDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleListResponseDto.java
  server/src/main/java/com/capstone/server/dto/SearchHistoryListDto.java
  server/src/main/java/com/capstone/server/repository/GuardianRepository.java
  server/src/main/java/com/capstone/server/repository/MissingPeopleRepository.java
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: ai, 📬 API

#162 Feat : 실종자 List 가져오기 api 변경, ai 탐색결과 가져오기 더미 api 생성
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/DetectionResultDto.java
  server/src/main/java/com/capstone/server/dto/SearchResultDto.java
  server/src/main/java/com/capstone/server/exception/CustomException.java
  server/src/main/java/com/capstone/server/model/SearchResultEntity.java
  server/src/main/java/com/capstone/server/model/enums/SearchResultSortBy.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: backend, 📬 API

#165 Feat : 탐색결과 가져오기 api 보충
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dataInitializer/CCTVInitializer.java
  server/src/main/java/com/capstone/server/dto/DetectionRequestDto.java
  server/src/main/java/com/capstone/server/dto/DetectionResultDto.java
  server/src/main/java/com/capstone/server/dto/SearchResultDto.java
  server/src/main/java/com/capstone/server/model/CCTVEntity.java
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: backend, 📬 API

#166 Fix: ProfileUrl original response
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
Labels: 🐞 bug, backend, 📬 API

#171 Fix : 버그수정 및 예외처리 추가
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dataInitializer/CCTVInitializer.java
  server/src/main/java/com/capstone/server/dto/CCTVDto.java
  server/src/main/java/com/capstone/server/model/enums/MissingPeopleSortBy.java
  server/src/main/java/com/capstone/server/model/enums/Status.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: 🐞 bug, backend

#169 Fix: main.yml change docker-compose.yml download path
  .github/workflows/main.yml
Labels: 🐞 bug, backend, Infra

#175 Feat : 보호자화면 api 구현
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/dto/guardian/BetweenPostRequestDto.java
  server/src/main/java/com/capstone/server/dto/guardian/DetectionResultForGuardianDto.java
  server/src/main/java/com/capstone/server/dto/guardian/MissingPeopleForGuardianDto.java
  server/src/main/java/com/capstone/server/model/BetweenEntity.java
  server/src/main/java/com/capstone/server/repository/BetweenRepository.java
  server/src/main/java/com/capstone/server/service/GuardianService.java
Labels: backend, 📬 API

#178 Docs: train 코드 수정에 관한 README 내 실행 방법 안내 변경
  ai/TextReID/README.md
Labels: 📃 doc, ai

#183 Feat : 실종자 현황(리스트) 화면 스크롤 페이지네이션 기능 구현
  frontend/.env
  frontend/src/components/missingPersonList/CardView.js
  frontend/src/core/api/index.js
  frontend/src/index.js
  frontend/src/pages/MissingPersonListPage.js
Labels: frontend, ✨feat

#184 Feat : 실종 정보 등록 설명 텍스트 추가
  frontend/src/components/addMisingPerson/AnnotationData.js
  frontend/src/components/addMisingPerson/AnnotationInfo.js
  frontend/src/data/WearingItemMenu.js
  frontend/src/pages/AddMissingPersonPage.js
Labels: frontend, 💄 design

#180 Fix: Frontend root api path
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: frontend, backend, Infra

#185 Feat : url단축 서비스 변경, 사용자 정보 암호화 진행
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/TestController.java
  server/src/main/java/com/capstone/server/dto/shortUrl/ShortUrlRequestDto.java
  server/src/main/java/com/capstone/server/dto/shortUrl/ShortUrlResponseDto.java
  server/src/main/java/com/capstone/server/exception/CustomException.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/EncryptionService.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: backend, 📬 API

#186 FIX: url 수정
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/TestController.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: backend, 📬 API

#189 fix : 보호자 페이지 쿼리 한국어로 가게 수정
  server/src/main/java/com/capstone/server/dto/guardian/MissingPeopleForGuardianDto.java
Labels: backend, 📬 API

#191 update : ai서버 yolo업데이트 및 ai서버 코드수정
  ai/app.py
  ai/yolov8/run.py
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/TestController.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: ai, backend

#193 Feat : 실종자 쿠키 받아오기
  frontend/package.json
  frontend/src/core/api/index.js
  frontend/src/core/cookie.js
  frontend/yarn.lock
  server/src/main/java/com/capstone/server/controller/GuardianController.java
Labels: frontend, ✨feat

#196 feat : 실종자 리포트 페이지 결합
  frontend/src/components/common/ResultView.js
  frontend/src/components/missingPersonList/CardView.js
  frontend/src/components/missingPersonReport/BasicInfo.js
  frontend/src/components/missingPersonReport/ReportList.js
  frontend/src/components/missingPersonReport/ReportTabs.js
  frontend/src/components/missingPersonReport/StepProgress.js
  frontend/src/core/api/index.js
  frontend/src/pages/MissingPersonReportPage.js
  frontend/yarn.lock
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
Labels: frontend, 📬 API

#197 Feat : 의뢰인용 이미지 선별 화면 api 연결
  frontend/src/components/guardianSelect/AllResultList.js
  frontend/src/components/guardianSelect/SelectImgList.js
  frontend/src/core/api/index.js
  frontend/src/pages/GuardianSelectImgPage.js
Labels: frontend, ✨feat, 📬 API

#202 Feat : api 추가
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/DetectionDataDto.java
  server/src/main/java/com/capstone/server/dto/DetectionResultDetailDto.java
  server/src/main/java/com/capstone/server/dto/SearchResultResponse.java
  server/src/main/java/com/capstone/server/dto/guardian/BetweenRequestDto.java
  server/src/main/java/com/capstone/server/dto/guardian/DetectionResultDto.java
  server/src/main/java/com/capstone/server/dto/guardian/DetectionResultForGuardianDto.java
  server/src/main/java/com/capstone/server/repository/BetweenRepository.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/response/SuccessResponse.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/GuardianService.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: backend, 📬 API

#205 Feat: 실종자 현황(리스트) 검색, 필터 기능 구현 및 api 연결
  frontend/.env
  frontend/src/components/missingPersonList/CardView.js
  frontend/src/core/api/index.js
  frontend/src/pages/MissingPersonListPage.js
Labels: frontend, ✨feat, 💄 design, 📬 API

#206 feat : 빠진 api 구현 -2
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/TestController.java
  server/src/main/java/com/capstone/server/dto/DetectionDataDto.java
  server/src/main/java/com/capstone/server/dto/DetectionResponseDto.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleListResponseDto.java
  server/src/main/java/com/capstone/server/dto/SearchRangeDto.java
  server/src/main/java/com/capstone/server/dto/SearchRequestDto.java
  server/src/main/java/com/capstone/server/dto/detectionResult/DetectionResultDetailDto.java
  server/src/main/java/com/capstone/server/dto/detectionResult/DetectionResultDto.java
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/GuardianService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
  server/src/main/java/com/capstone/server/service/SearchResultService.java
Labels: backend, 📬 API

#173 Fix : 버그 일으키는 파일 삭제
  ai/app.py
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleDetailResponseDto.java
Labels: 🐞 bug, backend

#209 Feat: ChatGPT API Service
  .vscode/settings.json
  server/build.gradle
  server/src/main/java/com/capstone/server/config/OpenAiConfig.java
  server/src/main/java/com/capstone/server/controller/ChatGPTController.java
  server/src/main/java/com/capstone/server/dto/ChatGPTRequest.java
  server/src/main/java/com/capstone/server/dto/ChatGPTResponse.java
  server/src/main/java/com/capstone/server/dto/Message.java
  server/src/main/java/com/capstone/server/service/ChatGPTService.java
Labels: backend, 📬 API

#215 Feature/chatgpt
  server/src/main/java/com/capstone/server/config/KafkaConsumerConfig.java
  server/src/main/java/com/capstone/server/config/KafkaProducerConfig.java
  server/src/main/java/com/capstone/server/controller/ChatGPTController.java
  server/src/main/java/com/capstone/server/controller/KafkaProducerController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java
  server/src/main/java/com/capstone/server/model/enums/BagType.java
  server/src/main/java/com/capstone/server/model/enums/BottomType.java
  server/src/main/java/com/capstone/server/model/enums/Color.java
  server/src/main/java/com/capstone/server/model/enums/HairStyle.java
  server/src/main/java/com/capstone/server/model/enums/TopType.java
  server/src/main/java/com/capstone/server/service/ChatGPTService.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
  server/src/main/java/com/capstone/server/service/KafkaProducerService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: backend, 📬 API

#216 Feat: Kafka For Second AI model
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
  server/src/main/java/com/capstone/server/service/KafkaProducerService.java
Labels: backend, 📬 API

#218 Update: TOP K set by giving argument
  ai/TextReID/lib/config/defaults.py
  ai/TextReID/lib/data/metrics/evaluation.py
  ai/TextReID/test_net.py
Labels: ai

#220 Update: Modified image similarity model
  ai/imageSearch/imgSearch.py
Labels: ai

#222 Update: Modified image similarity model for server
  ai/imageSearch/imgSearch_server.py
Labels: ai

#223 fix : api수정
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/detectionResult/DetectionResultDetailDto.java
  server/src/main/java/com/capstone/server/repository/BetweenRepository.java
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
  server/src/main/java/com/capstone/server/service/SearchResultService.java
Labels: ai, 📬 API

#230 Feat : 2차 탐색 ai 모델 도입
  ai/TextReID/test_net.py
  ai/app.py
  ai/imageSearch/__init__.py
  ai/imageSearch/imgSearch.py
  ai/imageSearch/imgSearch_server.py
  ai/imageSearch/readme.md
  ai/yolov5_crowdhuman/detect.py
  ai/yolov8/run.py
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/controller/TestController.java
  server/src/main/java/com/capstone/server/dto/SearchRangeDto.java
  server/src/main/java/com/capstone/server/dto/SearchResultDetailResponse.java
  server/src/main/java/com/capstone/server/dto/detection/DetectionResultDetailDto.java
  server/src/main/java/com/capstone/server/dto/detection/DetectionResultDto.java
  server/src/main/java/com/capstone/server/dto/detection/FirstDetectionDataDto.java
  server/src/main/java/com/capstone/server/dto/detection/FirstDetectionRequestDto.java
  server/src/main/java/com/capstone/server/dto/detection/SecondDetectionDataDto.java
  server/src/main/java/com/capstone/server/dto/detection/SecondDetectionRequestDto.java
  server/src/main/java/com/capstone/server/repository/BetweenRepository.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/GuardianService.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
  server/src/main/java/com/capstone/server/service/KafkaProducerService.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
  server/src/main/java/com/capstone/server/service/SearchResultService.java
Labels: ai, backend, 📬 API

#228 Fix: model Entity 수정 & chatgpt query 수정
  server/src/main/java/com/capstone/server/dto/ChatGPTRequest.java
  server/src/main/java/com/capstone/server/dto/MissingPeopleCreateRequestDto.java
  server/src/main/java/com/capstone/server/model/CCTVEntity.java
  server/src/main/java/com/capstone/server/model/MissingPeopleDetailEntity.java
  server/src/main/java/com/capstone/server/model/MissingPeopleEntity.java
  server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java
  server/src/main/java/com/capstone/server/service/ChatGPTService.java
Labels: backend, 📬 API

#232 Update : API추가 및 빠진요소 수정
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/StepDetailDto.java
  server/src/main/java/com/capstone/server/dto/StepDto.java
  server/src/main/java/com/capstone/server/repository/CCTVRepository.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SmsService.java
Labels: backend

#239 feat : get all marker first step,between and second step
  ai/app.py
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/MapCCTV.java
  server/src/main/java/com/capstone/server/repository/BetweenRepository.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/service/BetweenService.java
  server/src/main/java/com/capstone/server/service/SearchResultService.java
Labels: backend, 📬 API

#240 Feat: AI Second result save
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
Labels: backend, 📬 API

#241 Fix: server error
  server/src/main/java/com/capstone/server/config/KafkaConsumerConfig.java
  server/src/main/java/com/capstone/server/config/KafkaProducerConfig.java
  server/src/main/java/com/capstone/server/controller/CCTVController.java
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/dto/KafkaDto.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
  server/src/main/java/com/capstone/server/service/KafkaProducerService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: 🐞 bug, backend, 📬 API

#242 fix : 버그수정 및 응답 변경
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/service/SearchResultService.java
Labels: 🐞 bug, backend, 📬 API

#244 Chore : 실종정보 등록 추가 설명 텍스트 수정
  frontend/src/components/addMisingPerson/AnnotationData.js
  frontend/src/components/addMisingPerson/GuardianInfo.js
  frontend/src/data/WearingItemMenu.js
Labels: frontend, 🧹 chore

#247 Fix: github actions workflow Frontend Env
  .github/workflows/develop.yml
  .github/workflows/main.yml
Labels: frontend, Infra

#250 fix : 2차 탐색 종료 시 단계 수색으로 전환
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/KafkaConsumerService.java
Labels: ai, backend

#254 Feature : 탐색기록 Id로 마커띄우기 추가
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
  server/src/main/java/com/capstone/server/model/enums/Color.java
  server/src/main/java/com/capstone/server/service/BetweenService.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/SearchResultService.java
Labels: backend, 🧹 chore, 📬 API

#256 Fix : mapposition 버그수정
  server/src/main/java/com/capstone/server/controller/MissingPeopleController.java
Labels: 🐞 bug, backend

#258 Chore : 실종 정보 등록 토글 수정 및 추가
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/src/components/addMisingPerson/WearingInfo.js
  frontend/src/data/WearingItemMenu.js
  frontend/src/pages/AddMissingPersonPage.js
Labels: frontend, 🧹 chore

#259 chore : cctv 수정
  .gitignore
  ai/TextReID/.gitignore
  ai/TextReID/README.md
  ai/TextReID/datasets/cuhkpedes/annotations/annotations.json
  ai/TextReID/lib/data/datasets/cuhkpedes.py
  ai/TextReID/lib/data/metrics/evaluation.py
  ai/TextReID/test_net.py
  ai/app.py
  ai/forTest.py
  ai/imageSearch/imgSearch.py
  ai/imageSearch/imgSearch_server.py
  ai/imageSearch/readme.md
  ai/yolov8/run.py
  server/src/main/java/com/capstone/server/controller/CCTVController.java
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/model/SearchHistoryEntity.java
  server/src/main/java/com/capstone/server/repository/BetweenRepository.java
  server/src/main/java/com/capstone/server/repository/CCTVRepository.java
  server/src/main/java/com/capstone/server/repository/SearchResultRepository.java
  server/src/main/java/com/capstone/server/service/CCTVService.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
Labels: 🐞 bug, backend

#261 Hot fix : Cctv 가져오기 로직 버그수정
  server/src/main/java/com/capstone/server/repository/CCTVRepository.java
  server/src/main/java/com/capstone/server/service/CCTVService.java
  server/src/main/java/com/capstone/server/service/MissingPeopleService.java
Labels: 🐞 bug, backend

#264 Feat : 보호자용 화면 action 처리 및 ui 수정
  frontend/src/assets/icons/betweenStepIcon.svg
  frontend/src/assets/icons/findStepIcon.svg
  frontend/src/assets/icons/searchStepIcon.svg
  frontend/src/components/guardianMain/CustomSteps.js
  frontend/src/components/guardianMain/StepContents.js
  frontend/src/components/guardianSelect/AllResultList.js
  frontend/src/components/guardianSelect/SelectImgList.js
  frontend/src/core/api/index.js
  frontend/src/core/router.js
  frontend/src/pages/GuardianMainPage.js
  frontend/src/pages/GuardianSelectImgPage.js
  frontend/src/pages/GuardianShowResultPage.js
Labels: frontend, ✨feat, 🧹 chore, 📬 API

#270 Chore : 경찰 화면 반응형 수정
  frontend/src/components/missingPersonReport/IntelligentReportList.js
  frontend/src/components/reportIntelligent/IntelligentSearchBox.js
  frontend/src/components/reportIntelligent/IntelligentSearchOption.js
Labels: frontend, 🧹 chore

#272 Chore : 파비콘, 제목 수정
  frontend/public/favicon.png
  frontend/public/favicon2.png
  frontend/public/index.html
Labels: frontend, 🧹 chore

#265 Feat: README 최종본, TODO 남은 자료 추가 필수!
  README.md
  server/src/main/java/com/capstone/server/service/ChatGPTService.java
Labels: 📃 doc

#275 Docs: README 관련 문서 링크 업데이트
  README.md
Labels: 📃 doc

#280 fix : 스탭돌아가는 버그수정 및 알고리즘 수정#279
  server/src/main/java/com/capstone/server/repository/SearchHistoryRepository.java
  server/src/main/java/com/capstone/server/service/DetectService.java
  server/src/main/java/com/capstone/server/service/SearchHistoryService.java
Labels: backend, 📬 API

#283 fix : 상호작용단계 막아놓기
  server/src/main/java/com/capstone/server/controller/GuardianController.java
  server/src/main/java/com/capstone/server/service/GuardianService.java
Labels: 🐞 bug, 📬 API

#278 Docs: README 소개 영상 업데이트
  README.md
Labels: 📃 doc

#287 Feat: Login & Join
  server/build.gradle
  server/src/main/java/com/capstone/server/code/ErrorCode.java
  server/src/main/java/com/capstone/server/config/BCryptConfig.java
  server/src/main/java/com/capstone/server/config/JwtTokenFilter.java
  server/src/main/java/com/capstone/server/config/SecurityConfig.java
  server/src/main/java/com/capstone/server/controller/JwtLoginApiController.java
  server/src/main/java/com/capstone/server/controller/UserApiController.java
  server/src/main/java/com/capstone/server/dto/UserCreateRequestDto.java
  server/src/main/java/com/capstone/server/dto/UserUpdateRequestDto.java
  server/src/main/java/com/capstone/server/dto/login/JoinRequestDto.java
  server/src/main/java/com/capstone/server/dto/login/LoginRequestDto.java
  server/src/main/java/com/capstone/server/dto/login/LoginResponseDto.java
  server/src/main/java/com/capstone/server/model/UserEntity.java
  server/src/main/java/com/capstone/server/model/enums/UserRole.java
  server/src/main/java/com/capstone/server/repository/UserRepository.java
  server/src/main/java/com/capstone/server/service/JwtTokenService.java
  server/src/main/java/com/capstone/server/service/UserService.java
Labels: backend, 📬 API

#289 Fix : cors 수정 #288
  .gitignore
  server/src/main/java/com/capstone/server/config/WebConfig.java
Labels: 🐞 bug, backend, 📬 API

#290 fix : cors에러수정 #288
  server/src/main/java/com/capstone/server/config/WebConfig.java
Labels: 🐞 bug, backend, 📬 API

#291 Fix: docker server image set TimeZon Asia
  server/docker-compose.yml
Labels: 🐞 bug, backend, 📬 API

#292 delete: kafka TimeZone
  server/docker-compose.yml
Labels: 🐞 bug, backend, 📬 API

#294 Feat : 로그인 기능 추가
  frontend/src/App.js
  frontend/src/assets/icons/logo_b.svg
  frontend/src/assets/images/login_float1.svg
  frontend/src/assets/images/login_float2.svg
  frontend/src/assets/images/login_frame.svg
  frontend/src/components/addMisingPerson/MissingPersonInfo.js
  frontend/src/components/addMisingPerson/WearingInfo.js
  frontend/src/components/common/Nav.js
  frontend/src/components/missingPersonReport/ReportList.js
  frontend/src/core/api/api.js
  frontend/src/core/api/index.js
  frontend/src/core/router.js
  frontend/src/core/router/PrivateRoute.js
  frontend/src/core/router/index.js
  frontend/src/pages/AddMissingPersonPage.js
  frontend/src/pages/LoginPage.js
  frontend/src/pages/MissingPersonListPage.js
  frontend/src/pages/MissingPersonReportPage.js
Labels: frontend, ✨feat, 💄 design

#301 Chore : 시연용 지능형 탐색 범위 제한
  frontend/src/components/common/SearchBox.js
Labels: frontend, 🧹 chore

#304 Feat : 도움말 화면 추가
  frontend/src/assets/images/help_main.svg
  frontend/src/assets/images/help_select1.svg
  frontend/src/assets/images/help_select2.svg
  frontend/src/assets/images/help_select3.svg
  frontend/src/assets/images/help_select4.svg
  frontend/src/assets/images/help_select5.svg
  frontend/src/components/guardianMain/StepContents.js
  frontend/src/core/router/index.js
  frontend/src/pages/HelpMainPage.js
  frontend/src/pages/HelpPage.js
  frontend/src/pages/HelpSelectPage.js
Labels: frontend, 💄 design
